apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xdv7wejh8-go 
  janus-idp.io/tekton: xdv7wejh8-go
  backstage.io/kubernetes-id: xdv7wejh8-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xdv7wejh8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml